import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import ProvidersWrapper from './providers-wrapper';
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <ProvidersWrapper>
          <Header />
          <Box sx={{ p: 4, display: 'flex', justifyContent: 'center' }}>
            <Box sx={{ width: '100%', maxWidth: '1200px' }}>{children}</Box>
          </Box>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
